name: Build Checks

on: [push, pull_request]

jobs:
  Makefile-Commands:
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: lint
          - command: compile
          - command: install
    name: "Make Command ${{ matrix.command }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: ./configure apt
    - name: Build
      run: "make ${{ matrix.command }}"
